version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - straders-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://straders:straders@db/straders_db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - straders-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=straders
      - POSTGRES_PASSWORD=straders
      - POSTGRES_DB=straders_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - straders-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/spa:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    networks:
      - straders-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  straders-network:
    driver: bridge
